/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GroupProps } from '@react-three/fiber'

export function Platform(props: GroupProps) {
  const { nodes, materials } = useGLTF('/3d/PLATFORM.glb') as any
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder.geometry}
        material={materials['Material.006']}
        scale={[1, 0.5, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Monkey.geometry}
        material={materials['Material.001']}
        position={[-0.3, 0.269, 0.234]}
        rotation={[0, -1.352, 0]}
        scale={0.108}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube.geometry}
          material={materials['Material.001']}
          position={[0, 0.293, 0.016]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube001.geometry}
          material={materials['Material.002']}
          position={[0, -0.683, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube002.geometry}
          material={materials['Material.003']}
          position={[0, -0.683, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube003.geometry}
          material={materials['Material.002']}
          position={[0.276, -0.039, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube004.geometry}
          material={materials['Material.001']}
          position={[0, -0.683, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube005.geometry}
          material={materials['Material.001']}
          position={[0, -0.683, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube006.geometry}
          material={materials['Material.002']}
          position={[0.15, -0.493, -0.13]}
          rotation={[-0.25, 0.626, 0.569]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cubo.geometry}
          material={materials['Material.001']}
          position={[0, -0.683, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane.geometry}
          material={materials['Material.004']}
          position={[0, -0.683, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane001.geometry}
          material={materials['Material.002']}
          position={[0, -0.683, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Roundcube001.geometry}
          material={materials['Material.001']}
          position={[0, -0.683, 0]}
        />
      </mesh>
      <group position={[0, 0.09, 0]} rotation={[0, 0.192, 0]} scale={1.444}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle.geometry}
          material={materials['Material.007']}
          position={[0, -0.03, 0]}
          rotation={[0, -0.192, 0]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder001.geometry}
        material={materials['Material.007']}
        position={[-0.299, 0.185, 0.242]}
        scale={[0.186, 0.093, 0.186]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder002.geometry}
        material={materials['Material.007']}
        position={[-0.299, 0.115, 0.242]}
        scale={0.068}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder003.geometry}
        material={materials['Material.007']}
        position={[-0.557, 0.135, 0.242]}
        scale={[0.157, 0.079, 0.157]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder004.geometry}
        material={materials['Material.007']}
        position={[-0.557, 0.075, 0.242]}
        scale={0.058}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube007.geometry}
        material={nodes.Cube007.material}
        position={[-0.582, 0.114, -0.016]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube008.geometry}
          material={nodes.Cube008.material}
          position={[-0.037, -0.053, 0.034]}
          scale={0.06}
        />
      </mesh>
    </group>
  )
}

useGLTF.preload('/3d/PLATFORM.glb')
